### PR TITLE
Refactor Base Layout and Navbars

### PR DESCRIPTION
**Pull request by ENG3PLabs**
This PR updates the base layout and the navbars.

* removed a lot of whitespaces
* Bootstrap got bumped from 5.3.1 to 5.3.3
* Bootstrap icons got bumped from 1.10.5 to 1.11.3
* Translation got added to the top navbar

Also the index route is now a redirect to the /project route so that it can be changed in the future.

### CODE REVIEW

**Comment by ENG3PLabs** [comment]
Reopened the branch. Adding the redirect broke the ExampleTest.php. I will update this test.

Which create/edit buttons went missing because of the PRs?

**Comment by a13xh7** [comment]
I think create / edit  buttons for all models - projects, users, test cases. 
It's working right now in the chrome browser but I stil lcan't see those buttons in Opera, I cleared browser cache

**Comment by ENG3PLabs** [comment]
Downloading Opera...

**Comment by ENG3PLabs** [comment]
Ok, happens to me in Chrome too. Is related to the model branch. Still updating the unit tests for this branch though as they were failing.

**Comment by a13xh7** [comment]
finally, it works in opera, what is wrong with this browser.

**Pull request merged**
